config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  get 'commands/historique'
  get 'commands/during'
  get 'commands/import'
  get 'commands/export'
  resources :commands do
    collection { post :import }
  end

  root 'commands#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/command.rb
class Command < ApplicationRecord
  belongs_to :user

  validates :adress, presence: true
  validates :zipcode, presence: true, numericality: true
  validates_length_of :zipcode, is: 5
  validates :unit, presence: true, numericality: true




  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |command|
        csv << command.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)

    CSV.foreach(file.path, headers: true) do |row|
      commande = Command.create(:adress => row[0],:zipcode => row[1], :unit => row[4],:dateEnterFrom => row[2],:dateEnterTo => row[3],:commentaire => row[5])
      user = User.find(commande.user_id)
      commande.statewait=false
      commande.statedone=false
      if commande.zipcode.present?
        if (commande.zipcode > 75000) && (commande.zipcode < 75021)
          commande.price = user.price1
        else
          commande.price =  user.price2
        end
      end
      commande.usercommand = user.username

      if commande.dateEnterFrom == nil || commande.dateEnterFrom.strftime("%d/%m/%Y") < DateTime.now.strftime("%d/%m/%Y") || commande.dateEnterTo == nil || commande.dateEnterTo.strftime("%d/%m/%Y") < DateTime.now.strftime("%d/%m/%Y")
        commande.dateFinalFrom = Time.now
        commande.dateFinalFrom = Time.now
        commande.dateEnterFrom = Time.now
        commande.dateEnterTo = Time.now
        commande.asap = 1
      end
      commande.save
    end
  end

end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_command, only: [:show, :edit, :update, :destroy]

  # GET /commands
  # GET /commands.json
  def index
    init(false,false)

  end

  def historique
    @commands=nil
    if params[:search]
      if !current_user.admin?
        @commands = Command.search(params[:search]).where({usercommand: current_user})
      else
        @commands = Command.search(params[:search])
      end
    end
    front_date(@commands)
  end

# gestion des affichage par dateFinal
  def front_date (list)
    @listDate = []
    if !list.empty?
      firstDate = list.first.dateFinal
      list.each do |element|
        if firstDate.strftime("%d/%m/%Y") > element.dateFinal.strftime("%d/%m/%Y")
          firstDate = element.dateFinal
        end
      end

      @listDate.push(firstDate)
      dateBefore = firstDate
      list.each do |commande|
        if commande.dateFinal.strftime("%d/%m/%Y") > dateBefore.strftime("%d/%m/%Y")
          dateBefore=commande.dateFinal
          @listDate.push(commande.dateFinal)
        end
      end
    end
  end

  def init (condition1, condition2)


    @prixTotal=0
    @commands = []
    @tmpcommands = Command.all.order(params[:dateFinal])


    # gestion des affichages des commandes par trie d'admin et d'état

    @tmpcommands.each do |command|
      if (command.statewait == condition1 && command.statedone == condition2)
        if !current_user.admin?
          if command.user_id == current_user.id
            @commands.push(command)
          end
        else
          @commands.push(command)
        end
      end
    end
    # Affichage du total du prix
    @commands.each do |commande|
      @prixTotal += (commande.price * commande.unit)
    end
    front_date(@commands)
  end

  def during
    @prixTotal=0


    @commands = []
    @commandes = Command.all.order(params[:dateFinal])


    #trie des commandes par clients
    @commandes.each do |command|
      if (command.statewait == true || command.statedone == true)
        if !current_user.admin?
          if command.user_id == current_user.id
            @commands.push(command)
          end
        else
          @commands.push(command)
        end
      end
    end
    #créations du prix total sur les pages
    @commands.each do |commande|
      @prixTotal += commande.price * commande.unit
    end
    #création de liste de date pour l'affichage et le tri des commandes
    front_date(@commands)
  end

  def export

    commands = Command.all.where({dateFinal: "2017-06-31"})
    commands.each do |c|
      if current_user.admin != true
        commands = Command.all.where({dateFinal: "2017-06-30",usercommand: current_user.username})
      end
    end
    if !commands.nil?
      respond_to do |format|
        format.html
        format.csv { send_data commands.to_csv }
      end
    end
  end


  # GET /commands/1
  # GET /commands/1.json
  def show
  end

  # GET /commands/new
  def new
    @user=current_user
    @command = current_user.commands.new
  end

  # GET /commands/1/edit
  def edit
  end

  # POST /commands
  # POST /commands.json

  def create

    @user=current_user

    @command = @user.commands.new(command_params)
    @command.statewait=false
    @command.statedone=false

    # choix du prix de la commande
    if @command.zipcode.present?
      if (@command.zipcode > 75000) && (@command.zipcode < 75021)
        @command.price = current_user.price1
      else
        @command.price = current_user.price2
      end
    end
    #initialisation de la date normal selectionner
    @command.usercommand = current_user.username
    @command.dateFinal = @command.dateEnter
    @command.timeFinalFrom = @command.timeEnterFrom

    if @command.timeFinalFrom < @command.timeEnterTo
      @command.timeFinalTo = @command.timeEnterTo
    else
      @command.timeFinalTo = @command.dateFinal.change(hour:20)
    end
    #si modification lor de la création de l'admin
    if current_user.admin?
      @command.dateFinal = @command.dateModif
      @command.timeFinalFrom = @command.timeModifFrom
      @command.timeFinalTo = @command.timeModifTo
    end
    # cas de non ajout de la date
    if @command.dateFinal <= DateTime.now
      @command.dateFinal = DateTime.now
      @command.timeFinalFrom = @command.timeFinalTo.change(hour:9)
      @command.timeFinalTo = @command.timeFinalTo.change(hour:22)
      @command.asap = 1
    end
    # cas d'inversion de des horaires
    if @command.timeFinalFrom > @command.timeFinalTo
      tmpdate=@command.timeFinalFrom
      @command.timeFinalFrom = @command.timeFinalTo
      @command.timeFinalTo = tmpdate
    end

    respond_to do |format|
      if @command.save
        #CommandNotifierMailer.send_signup_email(@user,@command).deliver
        format.html { redirect_to commands_url, notice: 'Command was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  def day

  end
  # PATCH/PUT /commands/1
  # PATCH/PUT /commands/1.json
  def update
    if @command.dateModif.present?
        @command.dateFinal = @command.timeModifFrom
    end
    if @command.timeModifTo.present?
        @command.timeFinalTo = @command.timeModifTo
    end

    if @command.dateFinal > @command.timeFinalTo
      tmpdate=@command.dateFinal
      @command.dateFinal = @command.timeFinalTo
      @command.timeFinalTo = tmpdate
      @command.timeEnterFrom = @command.dateFinal
      @command.timeEnterTo = @command.timeFinalTo
    end

    respond_to do |format|
      if @command.update(command_params)
        format.html { redirect_to commands_during_url, notice: 'Command was successfully updated.' }

      else
        format.html { render :edit }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    current_user.commands.import(params[:file])
  end


  # DELETE /commands/1
  # DELETE /commands/1.json
  def destroy
    @command.destroy
    respond_to do |format|
      format.html { redirect_to commands_url, notice: 'Command was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_command
      @command = Command.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def command_params

        params.require(:command).permit(:adress,:zipcode,:unit,:timeEnterFrom,:dateEnter ,:timeEnterTo,:dateModif,:timeModifFrom ,:timeModifTo ,:commentaire,:statewait,:statedone)

    end
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/_form.html.erb
<div class="container">
  <%= form_for(@command) do |f| %>
    <% if command.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(command.errors.count, "error") %> prohibited this command from being saved:</h2>

        <ul>
        <% command.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">

      <div class="col-sm-8 field">
        <%= f.label :adress %><br><br>
        <%= f.text_field :adress , class: "form-control" %>
      </div>
      <div class="col-sm-2 field">
        <%= f.label :zipcode %><br><br>
        <%= f.text_field :zipcode, class: "form-control" %>
      </div><br>
    </div>
    <div class="row">
      <% if !current_user.admin? %>

        <div class="col-sm-3 field">
          <%= f.label :dateEnter %>
          <p>si pas de date format ASAP</p>
          <br>
          <%= f.date_select :dateEnter, class: "form-control" %>


        </div><br>
        <div class="col-sm-3 field">
          <p>From</p>
          <br>
          <%= f.time_select :timeEnterFrom, class: "form-control" %>

        </div><br>
        <div class="col-sm-2 field">

          <p>To</p>
          <br>
          <%= f.time_select :timeEnterTo, class: "form-control" %>

        </div><br>
      <% end %>
      <% if current_user.admin? %> <br>
        <div class="col-sm-3 datetime_field">
          <%= @command.dateFinal.strftime("%d/%m/%Y") %> <%= @command.timeFinalFrom.strftime("%Hh%M") %> <%= @command.timeFinalTo.strftime("%Hh%M") %>
          <p style="font-weight: bold;">Date modifié </p>
          <br>
          <%= f.date_select :dateModif, class: "form-control" %>
        </div><br>
        <div class="col-sm-2 field">
          <p style="font-weight: bold;">From</p>
          <br>
          <%= f.time_select :timeModifFrom, class: "form-control" %>
        </div>
        <div class="col-sm-3 field">
          <p style="font-weight: bold;">To</p>
          <br>
          <%= f.time_select :timeModifTo, class: "form-control" %>
        </div>
        <% end %>
        <div class="col-sm-2 field">
          <%= f.label :unit %><br><br>
          <%= f.text_field :unit, class: "form-control" %>
        </div>

    </div><br>
    <div class="row">
      <div class="col-sm-8 field">
        <%= f.label :commentaire %><br><br>
        <%= f.text_field :commentaire, class: "form-control" %>
      </div><br>

      <% if current_user.admin? %>
        <div >
          <% if @command.statewait != true %>
            <div class="col-sm-2 check_box">
                <p style="font-weight: bold;">Etat</p>
              <%= f.check_box :statewait %><p> En livraison</p> <br>
            </div><br>

          <%end%>

          <% if @command.statewait == true %>
            <div class="col-sm-2 check_box">
                <p style="font-weight: bold;">Etat</p>
              <%= f.check_box :statedone %><p> Livré</p> <br>
            </div><br>

          <%end%>
        </div><br>
      <% end %>
    </div>
    <div class="row">
      <div class="col-sm-5">
      </div>
      <% if !current_user.admin? %>
      <div class="col-sm-7 action">
        <%= f.submit "nouvelle commande",class: "btn btn-large btn-primary"%>
      </div>
      <%else%>
        <div class="col-sm-7 action">
          <%= f.submit "Modification de commande",class: "btn btn-large btn-primary"%>
        </div>
      <% end %>
    </div>
  <% end %>
  <h3 class="titre1">Importer des commandes par fichier csv</h3>
  <div class="row">
    <div class="col-sm-3"></div>

      <%= form_tag import_commands_path, multipart: true do %>
        <div class="col-sm-4"> <%= file_field_tag :file %></div>  <div class="col-sm-2"><%= submit_tag "Upload Commandes",class:"btn btn-large btn-primary" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/commands/during.html.erb
<div class="container">
  <div class="titre">
    <h1 class="titre1">Commandes en attente</h1>


    <br>
    <h3 class="titre2"></h3> <h1 class="titre3"> <%= @prixTotal %> €</h1>
  </div>

  <% @listDate.each do |date| %>
    <h2><%= date.strftime("%d/%m/%Y") %> </h2>
    <div class="media">
      <div class="media-body">
        <table class="table table-hover ">
          <thead>
            <tr>
              <th class="text-center">Adresse</th>
              <th class="text-center">Zipcode</th>
              <th class="text-center">Date</th>
              <th class="text-center">Date modifié</th>
              <th class="text-center">From</th>
              <th class="text-center">To</th>
              <th class="text-center">Format</th>
              <th class="text-center">Prix</th>
              <th class="text-center">Unité</th>
              <th class="text-center">Commentaire</th>
              <th class="text-center">État</th>
              <% if current_user.admin == true %>
                <th class="text-center">User</th>
              <% end %>
              <th colspan="4"></th>
            </tr>
          </thead>

          <tbody>
            <% @commands.each do |command| %>
              <% if  command.dateFinal.strftime("%d/%m/%Y") == date.strftime("%d/%m/%Y")%>
                <% if command.dateFinal.strftime("%d/%m/%Y") > DateTime.now.strftime("%d/%m/%Y") %>
                  <tr class="active text-center">
                <% elsif command.dateFinal.strftime("%d/%m/%Y") == DateTime.now.strftime("%d/%m/%Y") %>
                  <tr class="warning text-center ">
                <% else %>
                  <tr class="danger text-center ">
                <% end %>
                  <td><%= command.adress %></td>
                  <td><%= command.zipcode %></td>
                  <td><%= command.dateFinal.strftime("%d/%m/%Y") %></td>
                  <td><%= command.dateModif.strftime("%d/%m/%Y") if command.timeModifFrom.present?%></td>
                  <td><%= command.timeFinalFrom.strftime("%Hh%M")   %></td>
                  <td><%= command.timeFinalTo.strftime("%Hh%M")  %></td>
                  <% if command.asap != nil %>
                    <td>ASAP</td>
                  <% else %>
                    <td> </td>
                  <% end %>
                  <td><%= command.price %></td>
                  <td><%= command.unit %></td>
                  <td><%= command.commentaire %></td>
                  <% if command.statewait != true && command.statedone != true %>
                    <td>En attente</td>
                  <% end %>
                  <% if command.statewait == true && command.statedone != true %>
                    <td>En livraison</td>
                  <% end %>
                  <% if command.statedone == true %>
                    <td>Livré</td>
                  <% end %>
                  <% if current_user.admin == true %>
                    <td><%= command.usercommand%></td>
                  <% end %>
                  <% if (command.statewait != true && command.statedone != true) || current_user.admin == true %>
                    <td><%= link_to 'Edit', edit_command_path(command), class:'btn btn-warning btn-sm' %></td>
                    <td><%= link_to 'Destroy', command, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm' %></td>
                  <% end %>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div> <br>
  <% end %>
  <br><br>

  <p>
    Download:
    <%= link_to "CSV", commands_export_path(format: "csv") %>
  </p>

  <br>
</div>

app/views/commands/edit.html.erb
<h1 class="titre1">Editing Command</h1><br><br><br>

<%= render 'form', command: @command %>

app/views/commands/historique.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12"></div>
  </div>
  <div class="row">
    <div class="col-xs-3"></div>
    <div class="col-xs-6">
      <p id="notice"><%= notice %></p>
      <%= flash[:alert]%>
      <%=form_tag historique_path, :method => 'get' do%>
        <p>
          <%= date_select_tag :search, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :use_month_numbers => true, params[:search] %>
          <%= submit_tag "Search"%>
        </p>

      <%end%>
    </div>
    <div class="col-xs-3"></div>
  </div>
</div>


<% @listDate.each do |date| %>
  <h2><%= date %> </h2>
  <div class="media">
    <div class="media-body">
      <table class="table table-hover ">
        <thead>
          <tr>
            <th class="text-center">adresse</th>
            <th class="text-center">zipcode</th>
            <th class="text-center">date</th>
            <th class="text-center">date modifié</th>
            <th class="text-center">ASAP</th>
            <th class="text-center">prix</th>
            <th class="text-center">unité</th>
            <th class="text-center">commentaire</th>
            <th class="text-center">état</th>
            <% if current_user.admin == true %>
              <th class="text-center">User</th>
            <% end %>
            <th colspan="4"></th>
          </tr>
        </thead>

        <tbody>
          <% @commands.each do |command| %>
            <% if  command.dateBegin == date%>
              <% if command.dateBegin.strftime("%d/%m/%Y") > DateTime.now.strftime("%d/%m/%Y") %>
                <tr class="active text-center">
              <% elsif command.dateBegin.strftime("%d/%m/%Y") == DateTime.now.strftime("%d/%m/%Y") %>
                <tr class="warning text-center ">
              <% else %>
                <tr class="danger text-center ">
              <% end %>
                <td><%= command.adress %></td>
                <td><%= command.zipcode %></td>
                <td><%= command.dateBegin %></td>
                <td><%= command.dateEnd %></td>
                <% if command.asap != nil %>
                  <td>fils</td>
                <% else %>
                  <td> </td>
                <% end %>
                <td><%= command.price %></td>
                <td><%= command.unit %></td>
                <td><%= command.commentaire %></td>
                <% if command.statewait != true && command.statedone != true %>
                  <td>En attente</td>
                <% end %>
                <% if command.statewait == true && command.statedone != true %>
                  <td>En livraison</td>
                <% end %>
                <% if command.statedone == true %>
                  <td>Livré</td>
                <% end %>
                <% if current_user.admin == true %>
                  <td><%= command.usercommand%></td>
                <% end %>
                <td><%= link_to 'Show', command, class:'btn btn-primary btn-sm' %></td>
                <% if (command.statewait != true && command.statedone != true) || current_user.admin == true %>
                  <td><%= link_to 'Edit', edit_command_path(command), class:'btn btn-warning btn-sm' %></td>
                  <td><%= link_to 'Destroy', command, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm' %></td>
                <% end %>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div> <br>
<% end %>
<h3>Import Commandes</h3>
<%= form_tag import_commands_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Commandes" %>
<% end %>
<p>
  Download:
  <%= link_to "CSV", commands_export_path(format: "csv") %> |
  <%= link_to "Excel", commands_export_path(format: "xls") %>
</p>

<br>

app/views/commands/index.html.erb
<div class="container">
  <div class="titre">
    <h1 class="titre1">Commandes en attente</h1>


    <br>
    <h3 class="titre2"></h3> <h1 class="titre3"> <%= @prixTotal %> €</h1>
  </div>

  <% @listDate.each do |date| %>
    <h2><%= date.strftime("%d/%m/%Y") %> </h2>
    <div class="media">
      <div class="media-body">
        <table class="table table-hover ">
          <thead>
            <tr>
              <th class="text-center">Adresse</th>
              <th class="text-center">Zipcode</th>
              <th class="text-center">Date</th>
              <th class="text-center">Date modifié</th>
              <th class="text-center">From</th>
              <th class="text-center">To</th>
              <th class="text-center">Format</th>
              <th class="text-center">Prix</th>
              <th class="text-center">Unité</th>
              <th class="text-center">Commentaire</th>
              <th class="text-center">État</th>
              <% if current_user.admin == true %>
                <th class="text-center">User</th>
              <% end %>
              <th colspan="4"></th>
            </tr>
          </thead>

          <tbody>
            <% @commands.each do |command| %>
              <% if  command.dateFinal.strftime("%d/%m/%Y") == date.strftime("%d/%m/%Y")%>
                <% if command.dateFinal.strftime("%d/%m/%Y") > DateTime.now.strftime("%d/%m/%Y") %>
                  <tr class="active text-center">
                <% elsif command.dateFinal.strftime("%d/%m/%Y") == DateTime.now.strftime("%d/%m/%Y") %>
                  <tr class="warning text-center ">
                <% else %>
                  <tr class="danger text-center ">
                <% end %>
                  <td><%= command.adress %></td>
                  <td><%= command.zipcode %></td>
                  <td><%= command.dateFinal.strftime("%d/%m/%Y") %></td>
                  <td><%= command.dateModif.strftime("%d/%m/%Y") if command.timeModifFrom.present?%></td>
                  <td><%= command.timeFinalFrom.strftime("%Hh%M")   %></td>
                  <td><%= command.timeFinalTo.strftime("%Hh%M")  %></td>
                  <% if command.asap != nil %>
                    <td>ASAP</td>
                  <% else %>
                    <td> </td>
                  <% end %>
                  <td><%= command.price %></td>
                  <td><%= command.unit %></td>
                  <td><%= command.commentaire %></td>
                  <% if command.statewait != true && command.statedone != true %>
                    <td>En attente</td>
                  <% end %>
                  <% if command.statewait == true && command.statedone != true %>
                    <td>En livraison</td>
                  <% end %>
                  <% if command.statedone == true %>
                    <td>Livré</td>
                  <% end %>
                  <% if current_user.admin == true %>
                    <td><%= command.usercommand%></td>
                  <% end %>
                  <% if (command.statewait != true && command.statedone != true) || current_user.admin == true %>
                    <td><%= link_to 'Edit', edit_command_path(command), class:'btn btn-warning btn-sm' %></td>
                    <td><%= link_to 'Destroy', command, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm' %></td>
                  <% end %>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div> <br>
  <% end %>
  <br><br>

  <p>
    Download:
    <%= link_to "CSV", commands_export_path(format: "csv") %>
  </p>

  <br>
</div>

app/views/commands/new.html.erb
<h1 class="titre1">Nouvelle commande </h1> <br><br><br><br>

<%= render 'form', command: @command %>

app/views/commands/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_command_path(@command) %> |
<%= link_to 'Back', commands_path %>